/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.37
 * Generated at: 2016-11-18 00:45:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NewFile2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/zssjsp.jar", Long.valueOf(1475214068257L));
    _jspx_dependants.put("jar:file:/C:/Users/kissco/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/XmlProject/WEB-INF/lib/zssjsp.jar!/META-INF/zssjsp.tld", Long.valueOf(1464931522000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \r\n");
      out.write("    \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("    <title>My First ZK Spreadsheet JSP application</title>\r\n");
      out.write("    ");
      if (_jspx_meth_zssjsp_005fhead_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    .sheet1{\r\n");
      out.write("    \twidth: 95%;\r\n");
      out.write("    \theight: 50%;\r\n");
      out.write("    \ttop: 10%;\r\n");
      out.write("    \tposition: absolute;\r\n");
      out.write("    \talign: left;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .sheet2{\r\n");
      out.write("    \twidth: 95%;\r\n");
      out.write("    \theight: 50%;\r\n");
      out.write("    \ttop: 10%;\r\n");
      out.write("    \tposition: absolute;\r\n");
      out.write("    \tleft: 50%;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .btn{\r\n");
      out.write("    \tposition: absolute;\r\n");
      out.write("    \tleft: 43%;\r\n");
      out.write("    \ttop: 30%;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .file1{\r\n");
      out.write("    \ttop: 5%;\r\n");
      out.write("    \tposition: absolute;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .file2{\r\n");
      out.write("    \tleft: 50%;\r\n");
      out.write("    \ttop: 5%;\r\n");
      out.write("    \tposition: absolute;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .kbtn1{\r\n");
      out.write("    \ttop: 65%;\r\n");
      out.write("    \tposition: absolute;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .kbtn2{\r\n");
      out.write("    \tleft: 50%;\r\n");
      out.write("    \ttop: 65%;\r\n");
      out.write("    \tposition: absolute;\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("   \t\tfunction fos(){\r\n");
      out.write("   \t\t\tlocation.href = \"xmlCompare\";\r\n");
      out.write("   \t\t}\r\n");
      out.write("   \t\t\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function fileSelector1(){\r\n");
      out.write("\t//fileValue = document.getElementById(\"file1\").value;\r\n");
      out.write("\tvar fileValue = document.getElementById(\"file1\");\r\n");
      out.write("\talert(fileValue);\r\n");
      out.write("\t\r\n");
      out.write("\tvar url = fileValue.getAsDataURL();\r\n");
      out.write("\talert(url);\r\n");
      out.write("\t\r\n");
      out.write("\tlocation.href = \"fileValue?fileValue=fileValue.value\";\r\n");
      out.write("\t\r\n");
      out.write("\t//var zss1 = document.getElementById('myzss1');\r\n");
      out.write("\t//zss1.src = fileValue.src;\r\n");
      out.write("\t//return;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");

	String fileValue = (String)request.getAttribute("fileValue");
	if(fileValue == null){
		fileValue = "/WEB-INF/Book1.xlsx";
	}

      out.write("\r\n");
      out.write("<body class = \"canvas\">\r\n");
      out.write("<input type= \"file\" id = \"file1\" class = \"file1\" onchange=\"fileSelector1();\"/>\r\n");
      out.write("<div class = \"sheet1\">\r\n");
      out.write("    ");
      //  zssjsp:spreadsheet
      org.zkoss.zss.jsp.ui.SpreadsheetTag _jspx_th_zssjsp_005fspreadsheet_005f0 = (new org.zkoss.zss.jsp.ui.SpreadsheetTag());
      _jsp_getInstanceManager().newInstance(_jspx_th_zssjsp_005fspreadsheet_005f0);
      _jspx_th_zssjsp_005fspreadsheet_005f0.setJspContext(_jspx_page_context);
      // /NewFile2.jsp(89,4) null
      _jspx_th_zssjsp_005fspreadsheet_005f0.setDynamicAttribute(null, "id", "myzss1");
      // /NewFile2.jsp(89,4) null
      _jspx_th_zssjsp_005fspreadsheet_005f0.setDynamicAttribute(null, "src", fileValue);
      // /NewFile2.jsp(89,4) null
      _jspx_th_zssjsp_005fspreadsheet_005f0.setDynamicAttribute(null, "width", "40%");
      // /NewFile2.jsp(89,4) null
      _jspx_th_zssjsp_005fspreadsheet_005f0.setDynamicAttribute(null, "height", "100%");
      // /NewFile2.jsp(89,4) null
      _jspx_th_zssjsp_005fspreadsheet_005f0.setDynamicAttribute(null, "maxVisibleRows", "200");
      // /NewFile2.jsp(89,4) null
      _jspx_th_zssjsp_005fspreadsheet_005f0.setDynamicAttribute(null, "maxVisibleColumns", "40");
      // /NewFile2.jsp(89,4) null
      _jspx_th_zssjsp_005fspreadsheet_005f0.setDynamicAttribute(null, "showSheetbar", "true");
      _jspx_th_zssjsp_005fspreadsheet_005f0.doTag();
      _jsp_getInstanceManager().destroyInstance(_jspx_th_zssjsp_005fspreadsheet_005f0);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<input type= \"button\" class = \"btn\" value =\"比較\" onclick=\"fos();\"/>\r\n");
      out.write("<input type= \"file\" class = \"file2\"/>\r\n");
      out.write("<div class = \"sheet2\">\r\n");
      out.write("    ");
      if (_jspx_meth_zssjsp_005fspreadsheet_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<input type = \"button\" value = \"ファイル１確定\" class = \"kbtn1\"/>\r\n");
      out.write("<input type = \"button\" value = \"ファイル２確定\" class = \"kbtn2\"/>\r\n");
      out.write("\r\n");
      out.write("파일업로드<input type=\"file\" id=\"fileup\" onchange=\"this.select(); document.getElementById('filetext').value=document.selection.createRange().text.toString();\" />\r\n");
      out.write("실제 값<input type=\"text\" id=\"filetext\" />\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_zssjsp_005fhead_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  zssjsp:head
    org.zkoss.zss.jsp.ui.HeadTag _jspx_th_zssjsp_005fhead_005f0 = (new org.zkoss.zss.jsp.ui.HeadTag());
    _jsp_getInstanceManager().newInstance(_jspx_th_zssjsp_005fhead_005f0);
    _jspx_th_zssjsp_005fhead_005f0.setJspContext(_jspx_page_context);
    _jspx_th_zssjsp_005fhead_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_zssjsp_005fhead_005f0);
    return false;
  }

  private boolean _jspx_meth_zssjsp_005fspreadsheet_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  zssjsp:spreadsheet
    org.zkoss.zss.jsp.ui.SpreadsheetTag _jspx_th_zssjsp_005fspreadsheet_005f1 = (new org.zkoss.zss.jsp.ui.SpreadsheetTag());
    _jsp_getInstanceManager().newInstance(_jspx_th_zssjsp_005fspreadsheet_005f1);
    _jspx_th_zssjsp_005fspreadsheet_005f1.setJspContext(_jspx_page_context);
    // /NewFile2.jsp(94,4) null
    _jspx_th_zssjsp_005fspreadsheet_005f1.setDynamicAttribute(null, "id", "myzss2");
    // /NewFile2.jsp(94,4) null
    _jspx_th_zssjsp_005fspreadsheet_005f1.setDynamicAttribute(null, "src", "/WEB-INF/Book2.xlsx");
    // /NewFile2.jsp(94,4) null
    _jspx_th_zssjsp_005fspreadsheet_005f1.setDynamicAttribute(null, "width", "40%");
    // /NewFile2.jsp(94,4) null
    _jspx_th_zssjsp_005fspreadsheet_005f1.setDynamicAttribute(null, "height", "100%");
    // /NewFile2.jsp(94,4) null
    _jspx_th_zssjsp_005fspreadsheet_005f1.setDynamicAttribute(null, "maxVisibleRows", "200");
    // /NewFile2.jsp(94,4) null
    _jspx_th_zssjsp_005fspreadsheet_005f1.setDynamicAttribute(null, "maxVisibleColumns", "40");
    // /NewFile2.jsp(94,4) null
    _jspx_th_zssjsp_005fspreadsheet_005f1.setDynamicAttribute(null, "showSheetbar", "true");
    _jspx_th_zssjsp_005fspreadsheet_005f1.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_zssjsp_005fspreadsheet_005f1);
    return false;
  }
}
